openapi: 3.0.3
info:
  title: Hausverwaltung API
  version: 1.0.0
paths:

#user management
  /api/users:
    $ref: './paths/users.yaml'
  /api/user/{id}:
    $ref: './paths/user-details.yaml'

#building management
  /api/buildings:
    $ref: './paths/building.yaml'
  /api/building/{id}:
    $ref: './paths/building-details.yaml'

#ticket management
  /api/tickets:
    $ref: './paths/ticket.yaml'
  /api/ticket/{id}:
    $ref: './paths/ticket-details.yaml'

#mechanic management
  /api/mechanics:
    $ref: './paths/mechanic.yaml'
  /api/mechanic/{id}:
    $ref: './paths/mechanic-details.yaml'
