openapi: 3.0.3
info:
  title: Hausverwaltung API
  version: 1.0.0
paths:
  /api/users:
    $ref: './paths/users.yaml'


  /api/buildings:
    $ref: './paths/building.yaml'


  /api/tickets:
    $ref: './paths/ticket.yaml'